<?php include('_partials/_header.phtml'); ?>
<nav class="clearfix white bg-black">
    <div class="sm-col">
        <a href="<?php echo $router->pathFor('home') ?>" class="btn py2">Zones</a>
    </div>
    <div class="sm-col-right">
        <a href="<?php echo $router->pathFor('configure') ?>" class="btn py2">Configure</a>
    </div>
</nav>

<section class="container px2 py3">
    <h1 class="mt0">Configure <em><?php echo $name; ?></em></h1>


    <?php if (!is_null($configuration['subscription'])){ ?>
    <p>
        <strong> Group:</strong><br>
        <a href="#">
            <?php echo (is_null($configuration['group'])) ? 'none set' : $configuration['group'] ?>
        </a>
    </p>
    <?php } ?>

    <pre><?php var_dump($data); ?></pre>

    <form method="post">
        <label for="data"><?php echo $name; ?></label>
        <select name="data" class="block col-12 mb1 field">
            <?php foreach ($data as $value => $name) { ?>
                <option value="<?php echo $value; ?>"><?php echo $name; ?></option>
            <?php } ?>
        </select>

        <button type="submit" class="btn btn-primary">Save</button>
    </form>

</section>

<?php include('_partials/_footer.phtml'); ?>
