<?php include(templatePath('_partials/_header.phtml')); ?>

<section class="container px2 py3">
    <h1 class="mt0">Configuration</h1>


    <p>
        <strong>Subscription:</strong><br>
        <a href="<?php echo $router->pathFor('configureSubscription') ?>">
            <?php echo (is_null($configuration['subscription'])) ? 'none set' : $configuration['subscription'] ?>
        </a>
    </p>

    <?php if (!is_null($configuration['subscription'])){ ?>
    <p>
        <strong> Group:</strong><br>
        <a href="<?php echo $router->pathFor('configureGroup') ?>">
            <?php echo (is_null($configuration['group'])) ? 'none set' : $configuration['group'] ?>
        </a>
    </p>
    <?php } ?>
</section>

<?php include(templatePath('_partials/_footer.phtml')); ?>
