<html>
<head>
    <meta charset="utf-8"/>
    <title>Azure DNS Manager</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link href="/basscss.css" rel="stylesheet">

    <style type="text/css">
        html, body {
            background: #fff;
            font-size: 18px;
            line-height: 20px;
            color: #4d4d4d;
            margin: 0;
            padding: 0;
        }

        .btn-primary {
            border-radius: 0;
        }

        input {
            height: 2.25rem;
            padding: .5rem;
            vertical-align: middle;
            -webkit-appearance: none;
        }
    </style>
</head>
<body>
<?php include('_navigation.phtml'); ?>
